# For Ubuntu platform only

language: cpp
os:
  - linux
compiler:
  - gcc
notifications:
  email:
    on_success: always
    on_failure: always
before_install:
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install -qq libssl-dev libprotobuf-dev protobuf-compiler libboost-all-dev libcrypto++-dev libsqlite3-dev
script:
  - ./.jenkins
